services:
  server:
    build:
      context: .
    environment:
      MONGO_URL: "mongodb://db:27017"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    volumes:
      - db-data:/data/db
    expose:
      - 27017
volumes:
  db-data:
