openapi: 3.0.3
info:
  title: Todo collection's scheme
  version: 1.0.0
paths:
  /api/available:
    get:
      summary: Get available api versions.
      responses:
        '200':
          description: Available api versions.
          content:
            application/json:
              schema:
                type: array
                items:
                  enum: ['v1']
  /api/v1:
    get:
      summary: Get all todos
      description: Get all existing todos as a list.
      operationId: getToDos
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      description: Create a new todo
      operationId: addToDo
      requestBody:
        description: Create a new todo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Update an existing todo.
      description: Update an existing todo.
      operationId: updateToDo
      requestBody:
        description: The new todo content
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /api/v1/{id}:
    delete:
      parameters:
        - name: id
          in: path
          description: ToDo ID
          required: true
          schema:
            type: integer
            format: int64
      summary: Delete an existing todo.
      description: Delete an existing todo.
      operationId: deleteToDo
      responses:
        '200':
         description: Successful operation

components:
  schemas:
    Todo:
      required:
        - content
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        content:
          type: string
          description: 'The description of the item that needs to be done.'
          example: Buy stuff
        is_done:
          type: boolean
  requestBodies:
    Todo:
      description: Todo that needs to be created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todo'
